### ISSUE TITLE
US2000 Assertion Error

### ISSUE THREAD

**Issue by jasonmadigan** [Frankkkkk/python-pylontech#24]
```
Traceback (most recent call last):
  File "pylontech/pylontech.py", line 250, in <module>
    print(p.get_values_single(2))
  File "pylontech/pylontech.py", line 236, in get_values_single
    f = self.read_frame()
  File "pylontech/pylontech.py", line 186, in read_frame
    f = self._decode_hw_frame(raw_frame=raw_frame)
  File "pylontech/pylontech.py", line 167, in _decode_hw_frame
    assert got_frame_checksum == int(frame_chksum, 16)
AssertionError
```
Hooked up via instructions in readme. Dumping raw frames shows some data, but doesn't seem to decode:

```
b'\xb0\xf7\xf7\xf7\xf7w\xf7\xf7\xf7\xbf\xbf\xbf\xbf\xbf\xf7\xff\xbb\xbb\xef\x00~20024600C06E11020F0CA30CA50CA30CA30CA20CA40CA50CA30CA30CA50CA60CA50CA50CA50CA4050B0F0AF10AF10AF10AF10000BD9D157C02C3500283E517\r\x00'
```

it's a vanilla US2000, made in 2019

**Comment by petero-dk** [comment]
I sometimes see this error if I ask too quickly or if I accidentally have two processes asking at the same time on the same device.
