### ISSUE TITLE
Issue with python 3.9

### ISSUE THREAD

**Issue by Benoit3** [Frankkkkk/python-pylontech#38]
Hello,
I thank you for your scripts.

With python 3.9, only p.get_system_parameters() and p.get_values_single(2) provide results.

For other function, for example I get 
>>> p = pylontech.Pylontech()
>>> print(p.get_protocol_version())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/domotic/python-pylontech-master/pylontech/pylontech.py", line 242, in get_protocol_version
    return self.read_frame()
  File "/home/domotic/python-pylontech-master/pylontech/pylontech.py", line 215, in read_frame
    f = self._decode_hw_frame(raw_frame=raw_frame)
  File "/home/domotic/python-pylontech-master/pylontech/pylontech.py", line 196, in _decode_hw_frame
    assert got_frame_checksum == int(frame_chksum, 16)
ValueError: invalid literal for int() with base 16: b''

I think there is something wrong in send_cmd() parameters.
Can you help ?
Regards,
Benoit

**Comment by Benoit3** [comment]
I apologize.
After analysis, issue is not coming from python3 but from the fact that US5000 is more strict regarding protocol compliance => I will open new and detailed issue  for that.
